[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
edition = "2021"
version = "0.2.0"
description = """
The Rust Architecture for XML Binding
"""
rust-version = "1.78.0"
authors = ["H & D GmbH Open Source <contact-oss@h-d-gmbh.de>"]
license = "MIT"
repository = "https://github.com/hd-gmbh-dev/raxb"
categories = []
keywords = []

[workspace.dependencies]
raxb = { version = "0.2.0", path = "crates/raxb" }
raxb-derive = { version = "0.2.0", path = "crates/raxb-derive" }
raxb-validate = { version = "0.2.0", path = "crates/raxb-validate" }
raxb-xmlschema = { version = "0.2.0", path = "crates/raxb-xmlschema" }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
