name: Build and test

on:
  push:
    tags:
      - "v*"
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@1.78.0
    - name: Check
      run: |
        rustup component add clippy
        cargo clippy --no-deps
    - name: Build
      run: cargo build --release
    - name: Test
      run: cargo test
  publish:
    if: startsWith( github.ref, 'refs/tags/v' )
    uses: ./.github/workflows/publish.yaml
    needs: ci
    secrets: inherit