name: Publish to crates.io

on:
  workflow_call:
    secrets:
      CRATES_TOKEN:
        required: true
      BOT_GITHUB_TOKEN:
        required: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@1.78.0
    - name: Publish to crates.io.
      run: |
        cargo publish --token ${CRATES_TOKEN} -p raxb-derive
        cargo publish --token ${CRATES_TOKEN} -p raxb-xmlschema
        cargo publish --token ${CRATES_TOKEN} -p raxb-validate
        cargo publish --token ${CRATES_TOKEN} -p raxb
      env:
        CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
        SQLX_OFFLINE: true
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm publish --provenance --access public
      working-directory: ./packages/raxb-validate-wasm/dist
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  release:
      name: Release
      runs-on: ubuntu-latest
      needs: publish
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Release
          uses: actions/create-release@latest
          env:
            GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref }}
            release_name: ${{ github.ref }}
            draft: true
            prerelease: false