name: Publish to crates.io

on:
  workflow_call:
    secrets:
      CRATES_TOKEN:
        required: true
      BOT_GITHUB_TOKEN:
        required: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: dtolnay/rust-toolchain@1.84.0
    - name: get-cmake
      uses: lukka/get-cmake@latest
    - name: Publish to crates.io.
      run: |
        cargo publish --token ${CRATES_TOKEN} -p raxb-derive
        cargo publish --token ${CRATES_TOKEN} -p raxb-libxml2-sys
        cargo publish --token ${CRATES_TOKEN} -p raxb-xmlschema
        cargo publish --token ${CRATES_TOKEN} -p raxb
        cargo publish --token ${CRATES_TOKEN} -p raxb-xmlschema-build
        cargo publish --token ${CRATES_TOKEN} -p raxb-validate
        cargo publish --token ${CRATES_TOKEN} -p raxb-axum
      env:
        CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
  release:
      name: Release
      runs-on: ubuntu-latest
      needs: publish
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Release
          uses: actions/create-release@latest
          env:
            GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref }}
            release_name: ${{ github.ref }}
            draft: true
            prerelease: false